In [ ]:
# END TO END Deep  LEARNING PROJECT USING SIMPLE RNN 
# IMDB DATASET [MOVIE REVIEW DATASETS]

# REVIEW POSITIVE OR NEGATIVE 
# DATA SET--> FEATURE ENGINEERING --> SIMPLE RNN (TRAINING ) --> .H5 FILE--> STREAMLIT WEBAPP --> DEPLOYMENT 


# TRAINNG RNN 
# EMBEDDING LAYER + SIMPLE RNN

 
#  converting words to vectors using embedding layer 

In [1]:
# Options that we can use are 

# 1.)  One Hot representation (sparse matrix problem){Over Fitting}
# 2.)  Box of Words (sparse matrix problem)
# 3.)  Word2Vec (recommended)



In [1]:
# install tensorflow

%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [26]:
from tensorflow.keras.preprocessing.text import one_hot

In [28]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea ',
        'i am a good boy',
        'i am a  goof developer',
        'understand the meaning of words',
        'your videos are good']

In [29]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea ',
 'i am a good boy',
 'i am a  goof developer',
 'understand the meaning of words',
 'your videos are good']

In [30]:
voc_size = 10000

In [31]:
one_hot_repr = [one_hot(words, voc_size) for words in sent ]
one_hot_repr

[[1352, 3979, 5513, 3261],
 [1352, 3979, 5513, 1259],
 [1352, 2963, 5513, 2973],
 [3370, 9856, 7328, 7992, 7256],
 [3370, 9856, 7328, 2167, 3439],
 [6114, 1352, 5569, 5513, 9414],
 [7194, 5180, 6408, 7992]]

In [32]:
from tensorflow.keras.layers import Embedding 

from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences


In [33]:
import numpy as np 



In [34]:
sent_len = 8
embedded_docs = pad_sequences(one_hot_repr, padding ='pre', maxlen = sent_len)


In [35]:
embedded_docs

array([[   0,    0,    0,    0, 1352, 3979, 5513, 3261],
       [   0,    0,    0,    0, 1352, 3979, 5513, 1259],
       [   0,    0,    0,    0, 1352, 2963, 5513, 2973],
       [   0,    0,    0, 3370, 9856, 7328, 7992, 7256],
       [   0,    0,    0, 3370, 9856, 7328, 2167, 3439],
       [   0,    0,    0, 6114, 1352, 5569, 5513, 9414],
       [   0,    0,    0,    0, 7194, 5180, 6408, 7992]])

In [36]:
# feature Representation 

dim = 10

In [37]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')


In [39]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step


array([[[ 0.04586578, -0.01751823, -0.03806058,  0.02826801,
         -0.02995269, -0.01953673,  0.03178099,  0.02153793,
          0.02499917,  0.00945002],
        [ 0.04586578, -0.01751823, -0.03806058,  0.02826801,
         -0.02995269, -0.01953673,  0.03178099,  0.02153793,
          0.02499917,  0.00945002],
        [ 0.04586578, -0.01751823, -0.03806058,  0.02826801,
         -0.02995269, -0.01953673,  0.03178099,  0.02153793,
          0.02499917,  0.00945002],
        [ 0.04586578, -0.01751823, -0.03806058,  0.02826801,
         -0.02995269, -0.01953673,  0.03178099,  0.02153793,
          0.02499917,  0.00945002],
        [ 0.01322801, -0.0106517 , -0.02795171,  0.02489733,
          0.04183814, -0.04798039,  0.02990724, -0.01897582,
          0.03396405, -0.00464813],
        [ 0.00544236, -0.03947286,  0.03140726, -0.04211614,
         -0.02000999,  0.04720266, -0.03415602, -0.01512841,
         -0.03529548,  0.00406909],
        [-0.01562952,  0.00584543,  0.04744602,  0.0

In [41]:
embedded_docs[0]

array([   0,    0,    0,    0, 1352, 3979, 5513, 3261])

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[[ 0.04586578, -0.01751823, -0.03806058,  0.02826801,
         -0.02995269, -0.01953673,  0.03178099,  0.02153793,
          0.02499917,  0.00945002],
        [ 0.04586578, -0.01751823, -0.03806058,  0.02826801,
         -0.02995269, -0.01953673,  0.03178099,  0.02153793,
          0.02499917,  0.00945002],
        [ 0.04586578, -0.01751823, -0.03806058,  0.02826801,
         -0.02995269, -0.01953673,  0.03178099,  0.02153793,
          0.02499917,  0.00945002],
        [ 0.04586578, -0.01751823, -0.03806058,  0.02826801,
         -0.02995269, -0.01953673,  0.03178099,  0.02153793,
          0.02499917,  0.00945002],
        [ 0.01322801, -0.0106517 , -0.02795171,  0.02489733,
          0.04183814, -0.04798039,  0.02990724, -0.01897582,
          0.03396405, -0.00464813],
        [ 0.00544236, -0.03947286,  0.03140726, -0.04211614,
         -0.02000999,  0.04720266, -0.03415602, -0.01512841,
         -0.03529548,  0.00406909],
        [-0.01562952,  0.00584543,  0.04744602,  0.0